sudo: required

os:
  - linux
  - osx

osx_image: xcode7.3

services:
  - docker

language: node_js

env:
  global:
    - DOCKER_REPO=node:12;

# Caching so the next build will be fast too
cache:
  directories:
    - $HOME/node_modules

before_install:
  - set -e

install:
  - yarn install

before_script:

script:
  # Build the package, its tests and run the tests
  - yarn test

before_deploy:
  - echo "#TODO:/ publish to npm"

deploy:
  - echo "#TODO:/ publish to npm"
